### ISSUE TITLE
ModuleNotFoundError: No module named 'libml'

### ISSUE THREAD

**Issue by MRK4863** [walline/doublematch#1]
unable to import from module.
The issue arose from the script 'create_dataset.py'.

**Comment by walline** [comment]
Is the doublematch directory in your python path? Try

`export PYTHONPATH=$PYTHONPATH:"path to the DoubleMatch code"`

**Comment by MRK4863** [comment]
Thank you,
I was facing the issue when working on Google Colab.
Your suggestions worked, Thank you.
